apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: choreo-observability
  creationTimestamp: "2026-04-03T03:15:55Z"
  labels:
    app: prometheus-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.85.0
    chart: prometheus-76.0.0
    helm.toolkit.fluxcd.io/name: prometheus
    helm.toolkit.fluxcd.io/namespace: choreo-observability
    heritage: Helm
    release: prometheus
  name: prometheus-operator
  resourceVersion: "335642"
  uid: c6128cec-b387-4f2d-b0ff-3b1c4369739a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: openshift-monitoring
