apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: choreo-pdp
    meta.helm.sh/release-namespace: flux-system
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: choreo-pdp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.1
    helm.sh/chart: ingress-nginx-4.12.1
    helm.toolkit.fluxcd.io/name: choreo-pdp
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: ingress-nginx-controller
  namespace: choreo-webapps
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: choreo-pdp
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
