apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cilium",
          "interface": "eth0",
          "ips": [
              "10.128.17.81"
          ],
          "mac": "02:a7:46:b9:c2:5f",
          "default": true,
          "dns": {},
          "gateway": [
              "10.128.16.201"
          ]
      }]
    kubectl.kubernetes.io/default-container: main
    openshift.io/scc: privileged
    security.openshift.io/validated-scc-subject-type: serviceaccount
    workflows.argoproj.io/node-id: build-and-deploy-20000837005-610539686
    workflows.argoproj.io/node-name: build-and-deploy-20000837005.onExit
  creationTimestamp: "2026-04-16T04:10:50Z"
  generation: 1
  labels:
    category: deploy
    commit_sha: b70fe2e4e894f871f53a8ea3f6675613ba14afb9
    commit_tag: ""
    component_id: a8b1a675-f0a5-433d-b381-6d763ac9da6b
    git_ref_type: commit
    org_id: "83289"
    project_id: 2e232ef6-43d7-4778-a6ac-aac678454ec9
    step: environment-cleanup
    version_id: 7f2eff9c-9b13-4d5d-884c-60f095946b1b
    workflow_name: build-and-deploy-20000837005
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/on-exit: "true"
    workflows.argoproj.io/workflow: build-and-deploy-20000837005
  name: build-and-deploy-20000837005-environment-cleanup-step-610539686
  namespace: dp-builds-24835e72-7272-4b73-bb82-2929f5be4833
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: build-and-deploy-20000837005
    uid: 046221a0-6a46-4d4a-b37e-16467ee11faa
  resourceVersion: "9565313"
  uid: 4d551837-6ecf-4996-a392-6c9d4ce5b920
spec:
  containers:
  - command:
    - argoexec
    - wait
    - --loglevel
    - info
    - --log-format
    - text
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_WORKFLOW_NAME
      value: build-and-deploy-20000837005
    - name: ARGO_WORKFLOW_UID
      value: 046221a0-6a46-4d4a-b37e-16467ee11faa
    - name: ARGO_CONTAINER_NAME
      value: wait
    - name: ARGO_NODE_ID
      value: build-and-deploy-20000837005-610539686
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: choreoprivateacr.azurecr.io/argoproj/argoexec:v3.6.7
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mainctrfs/mnt/vol
      name: workspace
    - mountPath: /mainctrfs/mnt/secrets
      name: secret-volume
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /tmp
      name: tmp-dir-argo
      subPath: "0"
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
  - args:
    - /argo/staging/script
    command:
    - /var/run/argo/argoexec
    - emissary
    - --loglevel
    - info
    - --log-format
    - text
    - --
    - sh
    env:
    - name: GITOPS_TOKEN
      valueFrom:
        secretKeyRef:
          key: github-pat
          name: github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b
    - name: GITOPS_USER
      valueFrom:
        secretKeyRef:
          key: github-user
          name: github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b
    - name: GITOPS_EMAIL
      valueFrom:
        secretKeyRef:
          key: github-email
          name: github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b
    - name: WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          key: webhook-secret
          name: webhook-secret-a8b1a675-f0a5-433d-b381-6d763ac9da6b
    - name: STS_TOKEN
      valueFrom:
        secretKeyRef:
          key: sts-token
          name: sts-token-24835e72-7272-4b73-bb82-2929f5be4833
    - name: ARGO_CONTAINER_NAME
      value: main
    - name: ARGO_NODE_ID
      value: build-and-deploy-20000837005-610539686
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: choreoprivateacr.azurecr.io/choreoipaas/argo-environment-cleanup:main-cda6ea80714c9f4f09ab73c028e52cd913492f18
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/vol
      name: workspace
    - mountPath: /mnt/secrets
      name: secret-volume
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: choreo-image-pull-secret
  initContainers:
  - command:
    - argoexec
    - init
    - --loglevel
    - info
    - --log-format
    - text
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ARGO_POD_UID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: ARGO_WORKFLOW_NAME
      value: build-and-deploy-20000837005
    - name: ARGO_WORKFLOW_UID
      value: 046221a0-6a46-4d4a-b37e-16467ee11faa
    - name: ARGO_CONTAINER_NAME
      value: init
    - name: ARGO_TEMPLATE
      value: '{"name":"environment-cleanup-step","inputs":{},"outputs":{},"metadata":{"labels":{"category":"deploy","step":"environment-cleanup"}},"script":{"name":"","image":"choreoprivateacr.azurecr.io/choreoipaas/argo-environment-cleanup:main-cda6ea80714c9f4f09ab73c028e52cd913492f18","command":["sh"],"env":[{"name":"GITOPS_TOKEN","valueFrom":{"secretKeyRef":{"name":"github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b","key":"github-pat"}}},{"name":"GITOPS_USER","valueFrom":{"secretKeyRef":{"name":"github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b","key":"github-user"}}},{"name":"GITOPS_EMAIL","valueFrom":{"secretKeyRef":{"name":"github-config-a8b1a675-f0a5-433d-b381-6d763ac9da6b","key":"github-email"}}},{"name":"WEBHOOK_SECRET","valueFrom":{"secretKeyRef":{"name":"webhook-secret-a8b1a675-f0a5-433d-b381-6d763ac9da6b","key":"webhook-secret"}}},{"name":"STS_TOKEN","valueFrom":{"secretKeyRef":{"name":"sts-token-24835e72-7272-4b73-bb82-2929f5be4833","key":"sts-token"}}}],"resources":{"limits":{"cpu":"1","memory":"1000Mi"},"requests":{"cpu":"500m","memory":"500Mi"}},"volumeMounts":[{"name":"workspace","mountPath":"/mnt/vol"},{"name":"secret-volume","mountPath":"/mnt/secrets"}],"securityContext":{"privileged":true},"source":"#!/bin/sh\nset
        -e\nscript_dir=/usr/src/app\ncd /mnt/vol\nnode $script_dir/gitops-checkout.js
        --GIT_USERNAME $GITOPS_USER --GIT_EMAIL $GITOPS_EMAIL --GIT_PAT $GITOPS_TOKEN
        --REPO_URL https://github.com/choreo-userapps-gitops-prod/53e6317cb524-client-configs.git
        --BRANCH main\ncd 53e6317cb524-client-configs\nrm -rf scanResult\nif [ -d
        \"/mnt/vol/scanResult\" ]; then\n    mv /mnt/vol/scanResult .\nelse\n    echo
        \"Directory /mnt/vol/scanResult does not exist\"\nfi\nmkdir -p configs\nif
        [ -f \"/mnt/vol/cilium-testing/service-to-service/project-level/client/choreo-config-schema.json\"
        ]; then\n    mv /mnt/vol/cilium-testing/service-to-service/project-level/client/choreo-config-schema.json
        configs/\nelif [ -f \"/mnt/vol/cilium-testing/service-to-service/project-level/client/generated-artifacts/configs/config-schema.json\"
        ]; then\n    cp /mnt/vol/cilium-testing/service-to-service/project-level/client/generated-artifacts/configs/config-schema.json
        configs/choreo-config-schema.json\nelse\n    echo \"Directory /mnt/vol/cilium-testing/service-to-service/project-level/client/choreo-config-schema.json
        does not exist\"\nfi\nif [ -f \"$(git rev-parse --git-dir)/shallow\" ] \u0026\u0026
        git rev-parse --is-shallow-repository; then\n  git fetch --unshallow\nelse\n  echo
        \"Repository is already complete. No need to unshallow.\"\nfi\necho \"Component
        ID: a8b1a675-f0a5-433d-b381-6d763ac9da6b\" \u003e\u003e info.txt\necho \"Project
        ID: 2e232ef6-43d7-4778-a6ac-aac678454ec9\" \u003e\u003e info.txt\necho \"Org
        ID: 83289\" \u003e\u003e info.txt\necho \"Commit SHA: b70fe2e4e894f871f53a8ea3f6675613ba14afb9\"
        \u003e\u003e info.txt\necho \"Workflow Name: build-and-deploy-20000837005\"
        \u003e\u003e info.txt\ngit add .\ngit commit -m ''Update info.txt''\nif git
        push origin main ; then\n   echo \"Changes pushed successfully\"\nelse\n   git
        fetch origin\n   git merge --no-edit --strategy recursive --strategy-option
        theirs origin/main\n   git push origin main\nfi\nGITOPS_HASH=$(git rev-parse
        HEAD)\ncd ..\nif [ \"Failed\" = \"Succeeded\" ]; then\n   conclusion=\"success\"\nelse\n   conclusion=\"failure\"\nfi\nnode
        $script_dir/configurable-generation-status-update.js --baseURL=https://app.choreo.dev
        --componentId=a8b1a675-f0a5-433d-b381-6d763ac9da6b --versionId=7f2eff9c-9b13-4d5d-884c-60f095946b1b
        --configMappingId=64C074BF-5A36-F111-8EF3-6045BDB78961 --status=completed
        --sourceCommit=b70fe2e4e894f871f53a8ea3f6675613ba14afb9 --gitOpsCommit $GITOPS_HASH
        --conclusion=$conclusion --token=$WEBHOOK_SECRET\nset +e  # Don''t exit on
        error\nif [ \"Failed\" = \"Succeeded\" ]; then\n   node $script_dir/build-deploy-action.js
        --domain https://app.choreo.dev --org-id 24835e72-7272-4b73-bb82-2929f5be4833
        --project-id 2e232ef6-43d7-4778-a6ac-aac678454ec9 --app-id a8b1a675-f0a5-433d-b381-6d763ac9da6b
        --env-id f9e3c720-d239-4f85-b835-cf8229c13bb5 --version 7f2eff9c-9b13-4d5d-884c-60f095946b1b
        --image-name 53e6317cb524-client-configs --git-hash b70fe2e4e894f871f53a8ea3f6675613ba14afb9
        --gitops-hash $GITOPS_HASH --token $WEBHOOK_SECRET --container-id ed5ef9aa-6327-40c2-8278-d9b6cd64ea74
        --is-container-deployment true --oas-file-path $OAS_FILE_PATH --is-auto-deploy
        false --run-id 20000837005 --choreo-app 53e6317cb524-client-configs\nfi\nconclusionStepsExitCode=$?\nset
        -e  # Restore exit on error\nif [ $conclusionStepsExitCode -ne 0 ]; then\n  echo
        \"Warning: conclusionSteps failed with exit code $conclusionStepsExitCode\"\nfi\nif
        [ -z \"$conclusionStepsExitCode\" ]; then\n   conclusionStepsExitCode=0\nfi\nif
        [ \"Failed\" = \"Succeeded\" ] \u0026\u0026 [ \"$conclusionStepsExitCode\"
        -eq 0 ]; then\n   conclusion=\"success\"\nelse\n   conclusionStepsExitCode=1\n   conclusion=\"failure\"\nfi\nexport
        $(cat /mnt/vol/.env | xargs) \u003e /dev/null 2\u003e\u00261\nsh $script_dir/status-update.sh
        --baseurl=https://apis.choreo.dev --componentId=a8b1a675-f0a5-433d-b381-6d763ac9da6b
        --trackId=7f2eff9c-9b13-4d5d-884c-60f095946b1b --workflowName=build-and-deploy-20000837005
        --status=completed --conclusion=$conclusion --token=$STS_TOKEN --gitOpsCommitSha=$GITOPS_HASH
        --metadata=$encodedSrcConfigDetails\nif [ \"Failed\" != \"Succeeded\" ] ||
        [ \"$conclusionStepsExitCode\" -ne 0 ]; then\n  echo \"ArgoBuildOfComponentFailed.OrgID:24835e72-7272-4b73-bb82-2929f5be4833,ProjectID:2e232ef6-43d7-4778-a6ac-aac678454ec9,ComponentID:a8b1a675-f0a5-433d-b381-6d763ac9da6b,VersionID:7f2eff9c-9b13-4d5d-884c-60f095946b1b\"\nfi\nexit
        $conclusionStepsExitCode"}}'
    - name: ARGO_NODE_ID
      value: build-and-deploy-20000837005-610539686
    - name: ARGO_INCLUDE_SCRIPT_OUTPUT
      value: "false"
    - name: ARGO_DEADLINE
      value: "0001-01-01T00:00:00Z"
    - name: ARGO_PROGRESS_FILE
      value: /var/run/argo/progress
    - name: ARGO_PROGRESS_PATCH_TICK_DURATION
      value: 1m0s
    - name: ARGO_PROGRESS_FILE_TICK_DURATION
      value: 3s
    image: choreoprivateacr.azurecr.io/argoproj/argoexec:v3.6.7
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
  nodeName: ip-10-0-28-234.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: dp-builds-24835e72-7272-4b73-bb82-2929f5be4833-sa
  serviceAccountName: dp-builds-24835e72-7272-4b73-bb82-2929f5be4833-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: var-run-argo
  - emptyDir: {}
    name: tmp-dir-argo
  - name: workspace
    persistentVolumeClaim:
      claimName: build-and-deploy-20000837005-workspace
  - name: secret-volume
    secret:
      defaultMode: 420
      secretName: registry-secret-2e232ef6-43d7-4778-a6ac-aac678454ec9
  - emptyDir: {}
    name: argo-staging
  - name: kube-api-access-pdgs4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-04-16T04:11:10Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-04-16T04:10:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-04-16T04:11:08Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-04-16T04:11:08Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-04-16T04:10:50Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 500m
      memory: 500Mi
    containerID: cri-o://19a1a195565f66f06c008b8f60d6fb056d6e8aae0fed78accc7812c9fb1c881d
    image: choreoprivateacr.azurecr.io/choreoipaas/argo-environment-cleanup:main-cda6ea80714c9f4f09ab73c028e52cd913492f18
    imageID: choreoprivateacr.azurecr.io/choreoipaas/argo-environment-cleanup@sha256:5532d5db25715b601eb6692e304457f22968745b70f3dfb142a7bf47207294d2
    lastState: {}
    name: main
    ready: false
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://19a1a195565f66f06c008b8f60d6fb056d6e8aae0fed78accc7812c9fb1c881d
        exitCode: 1
        finishedAt: "2026-04-16T04:11:07Z"
        reason: Error
        startedAt: "2026-04-16T04:11:05Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /mnt/vol
      name: workspace
    - mountPath: /mnt/secrets
      name: secret-volume
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: cri-o://8352e280a16ea4364f2cdc78136da847adf4903c8f2206be572f3694607dc825
    image: choreoprivateacr.azurecr.io/argoproj/argoexec:v3.6.7
    imageID: choreoprivateacr.azurecr.io/argoproj/argoexec@sha256:f990ff9bc9ebd08d8a064634f70f3bab5cdc55a4b727f31a471bb5eb9995bb21
    lastState: {}
    name: wait
    ready: false
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://8352e280a16ea4364f2cdc78136da847adf4903c8f2206be572f3694607dc825
        exitCode: 0
        finishedAt: "2026-04-16T04:11:08Z"
        reason: Completed
        startedAt: "2026-04-16T04:10:59Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /mainctrfs/mnt/vol
      name: workspace
    - mountPath: /mainctrfs/mnt/secrets
      name: secret-volume
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /tmp
      name: tmp-dir-argo
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.28.234
  hostIPs:
  - ip: 10.0.28.234
  initContainerStatuses:
  - containerID: cri-o://981a9f024eef0c87da2c3fdb50a0edbf807760a957e105633e7d758e353d25f1
    image: choreoprivateacr.azurecr.io/argoproj/argoexec:v3.6.7
    imageID: choreoprivateacr.azurecr.io/argoproj/argoexec@sha256:f990ff9bc9ebd08d8a064634f70f3bab5cdc55a4b727f31a471bb5eb9995bb21
    lastState: {}
    name: init
    ready: true
    resources: {}
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://981a9f024eef0c87da2c3fdb50a0edbf807760a957e105633e7d758e353d25f1
        exitCode: 0
        finishedAt: "2026-04-16T04:10:56Z"
        reason: Completed
        startedAt: "2026-04-16T04:10:56Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/argo
      name: var-run-argo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pdgs4
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Failed
  podIP: 10.128.17.81
  podIPs:
  - ip: 10.128.17.81
  qosClass: Burstable
  startTime: "2026-04-16T04:10:50Z"
