apiVersion: v1
kind: Pod
metadata:
  name: debug-image-push
  namespace: dp-builds-24835e72-7272-4b73-bb82-2929f5be4833
spec:
  imagePullSecrets:
  - name: choreo-image-pull-secret
  containers:
  - name: debug
    image: choreoprivateacr.azurecr.io/choreoipaas/argo-image-push:main-e664c3a01461d0b1d196d5976c524fe15277abab
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
    volumeMounts:
    - mountPath: /mnt/secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: registry-secret-2e232ef6-43d7-4778-a6ac-aac678454ec9
  restartPolicy: Never
