
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: request-drop-test-client
spec:
  selector:
    matchLabels:
      app: request-drop-test-client
      client: request-drop-test
  template:
    metadata:
      labels:
        app: request-drop-test-client
        client: request-drop-test
    spec:
      containers:
      - name: curl
        image: registry.access.redhat.com/ubi8/ubi:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            HTTP_CODE=$(curl -o /dev/null -s -w "%{http_code}" -m 30 http://request-drop-test-server)
            echo "HTTP_CODE: $HTTP_CODE TIME: $(date +%s)"
            if [ "$HTTP_CODE" -ne 200 ]; then
              exit 1
            fi
          done
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: request-drop-test-server
spec:
  selector:
    matchLabels:
      app: request-drop-test-server
      server: request-drop-test
  template:
    metadata:
      labels:
        app: request-drop-test-server
        server: request-drop-test
      annotations:
        policy.cilium.io/proxy-visibility: "<Egress/53/UDP/DNS>,<Ingress/8080/TCP/HTTP>"
    spec:
      containers:
      - name: nginx
        image: quay.io/nginx/nginx-unprivileged:stable
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: request-drop-test-server
spec:
  selector:
    app: request-drop-test-server
    server: request-drop-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
